blue:
  - - ['gh', 6, 1]
    - ['rs', 3, 2]
    - ['bv', 1, 4]
    - ['yo', 5, 6]
    - ['wh', 6, 1]
    - ['wh', 3, 3]
    - ['wh', 7, 3]
    - ['wh', 1, 4]
    - ['wh', 5, 7]
    - ['wv', 6, 1]
    - ['wv', 3, 2]
    - ['wv', 2, 4]
    - ['wv', 6, 6]
    - ['wv', 3, 7]
  - - ['bv', 5, 1]
    - ['yo', 1, 3]
    - ['rs', 6, 5]
    - ['gh', 2, 6]
    - ['wh', 5, 2]
    - ['wh', 1, 4]
    - ['wh', 7, 4]
    - ['wh', 6, 5]
    - ['wh', 2, 6]
    - ['wv', 5, 1]
    - ['wv', 2, 3]
    - ['wv', 7, 5]
    - ['wv', 2, 6]
    - ['wv', 4, 7]
  - - ['gh', 3, 2]
    - ['rs', 5, 3]
    - ['bv', 2, 4]
    - ['yo', 4, 5]
    - ['wh', 3, 2]
    - ['wh', 2, 4]
    - ['wh', 5, 4]
    - ['wh', 7, 4]
    - ['wh', 4, 6]
    - ['wv', 3, 2]
    - ['wv', 5, 3]
    - ['wv', 3, 4]
    - ['wv', 5, 5]
    - ['wv', 2, 7]
  - - ['bv', 3, 0]
    - ['rs', 6, 2]
    - ['yo', 1, 5]
    - ['gh', 2, 5]
    - ['wh', 3, 0]
    - ['wh', 7, 0]
    - ['wh', 6, 1]
    - ['wh', 2, 5]
    - ['wh', 1, 6]
    - ['wv', 3, 0]
    - ['wv', 7, 2]
    - ['wv', 2, 5]
    - ['wv', 5, 7]
    - ['rd', 0, 3]
    - ['bi', 5, 6]
green:
  - - ['ro', 4, 1]
    - ['bs', 1, 2]
    - ['gv', 6, 5]
    - ['yh', 1, 6]
    - ['wh', 4, 1]
    - ['wh', 7, 2]
    - ['wh', 1, 3]
    - ['wh', 1, 6]
    - ['wh', 6, 6]
    - ['wv', 5, 1]
    - ['wv', 1, 2]
    - ['wv', 7, 5]
    - ['wv', 1, 6]
    - ['wv', 3, 7]
  - - ['bs', 4, 1]
    - ['yh', 1, 4]
    - ['gv', 6, 5]
    - ['ro', 3, 6]
    - ['wh', 4, 1]
    - ['wh', 7, 2]
    - ['wh', 1, 4]
    - ['wh', 6, 6]
    - ['wh', 3, 7]
    - ['wv', 5, 1]
    - ['wv', 1, 4]
    - ['wv', 6, 5]
    - ['wv', 4, 6]
    - ['wv', 6, 7]
  - - ['bs', 3, 1]
    - ['ro', 6, 3]
    - ['yh', 1, 4]
    - ['gv', 4, 6]
    - ['wh', 7, 1]
    - ['wh', 3, 2]
    - ['wh', 6, 3]
    - ['wh', 1, 4]
    - ['wh', 4, 7]
    - ['wv', 3, 1]
    - ['wv', 7, 3]
    - ['wv', 1, 4]
    - ['wv', 5, 6]
    - ['wv', 6, 7]
  - - ['bs', 4, 1]
    - ['gv', 5, 1]
    - ['yh', 1, 3]
    - ['ro', 6, 4]
    - ['wh', 4, 1]
    - ['wh', 5, 2]
    - ['wh', 7, 2]
    - ['wh', 1, 3]
    - ['wh', 6, 5]
    - ['wv', 5, 1]
    - ['wv', 1, 3]
    - ['wv', 7, 4]
    - ['wv', 2, 7]
    - ['yd', 2, 0]
    - ['gi', 3, 6]
red:
  - - ['ys', 6, 1]
    - ['rv', 0, 2]
    - ['go', 5, 3]
    - ['bh', 2, 5]
    - ['wh', 0, 2]
    - ['wh', 6, 2]
    - ['wh', 7, 3]
    - ['wh', 5, 4]
    - ['wh', 2, 5]
    - ['wv', 7, 1]
    - ['wv', 1, 2]
    - ['wv', 5, 3]
    - ['wv', 2, 5]
    - ['wv', 4, 7]
  - - ['ys', 0, 2]
    - ['bh', 5, 3]
    - ['go', 1, 5]
    - ['rv', 6, 6]
    - ['wh', 7, 2]
    - ['wh', 0, 3]
    - ['wh', 5, 3]
    - ['wh', 1, 6]
    - ['wh', 6, 6]
    - ['wv', 1, 2]
    - ['wv', 5, 3]
    - ['wv', 1, 5]
    - ['wv', 7, 6]
    - ['wv', 4, 7]
  - - ['bh', 4, 1]
    - ['ys', 2, 2]
    - ['rv', 6, 4]
    - ['go', 3, 6]
    - ['wh', 4, 1]
    - ['wh', 7, 2]
    - ['wh', 2, 3]
    - ['wh', 6, 4]
    - ['wh', 3, 7]
    - ['wv', 4, 1]
    - ['wv', 3, 2]
    - ['wv', 7, 4]
    - ['wv', 3, 6]
    - ['wv', 6, 7]
  - - ['ys', 2, 1]
    - ['rv', 4, 3]
    - ['go', 5, 3]
    - ['bh', 1, 5]
    - ['wh', 2, 2]
    - ['wh', 4, 3]
    - ['wh', 5, 4]
    - ['wh', 1, 5]
    - ['wh', 7, 5]
    - ['wv', 3, 1]
    - ['wv', 5, 3]
    - ['wv', 1, 5]
    - ['wv', 3, 7]
    - ['yd', 1, 4]
    - ['bd', 3, 6]
yellow:
  - - ['kp', 0, 2]
    - ['rh', 5, 2]
    - ['gs', 2, 3]
    - ['yv', 6, 4]
    - ['bo', 1, 6]
    - ['wh', 7, 1]
    - ['wh', 0, 2]
    - ['wh', 5, 2]
    - ['wh', 2, 4]
    - ['wh', 6, 5]
    - ['wh', 1, 6]
    - ['wv', 0, 2]
    - ['wv', 5, 2]
    - ['wv', 3, 3]
    - ['wv', 6, 4]
    - ['wv', 2, 6]
    - ['wv', 4, 7]
  - - ['kp', 4, 0]
    - ['bo', 2, 1]
    - ['yv', 1, 3]
    - ['gs', 6, 4]
    - ['rh', 5, 6]
    - ['wh', 4, 0]
    - ['wh', 2, 2]
    - ['wh', 7, 3]
    - ['wh', 1, 4]
    - ['wh', 6, 4]
    - ['wh', 5, 6]
    - ['wv', 4, 0]
    - ['wv', 2, 1]
    - ['wv', 2, 3]
    - ['wv', 7, 4]
    - ['wv', 5, 6]
    - ['wv', 3, 7]
  - - ['yv', 6, 1]
    - ['gs', 1, 2]
    - ['rh', 4, 3]
    - ['kp', 0, 5]
    - ['bo', 2, 6]
    - ['wh', 6, 2]
    - ['wh', 1, 3]
    - ['wh', 4, 3]
    - ['wh', 7, 4]
    - ['wh', 0, 5]
    - ['wh', 2, 6]
    - ['wv', 6, 1]
    - ['wv', 2, 2]
    - ['wv', 4, 3]
    - ['wv', 0, 5]
    - ['wv', 3, 6]
    - ['wv', 5, 7]
  - - ['kp', 2, 0]
    - ['rh', 6, 2]
    - ['gs', 4, 4]
    - ['bo', 5, 4]
    - ['yv', 1, 5]
    - ['wh', 2, 0]
    - ['wh', 7, 1]
    - ['wh', 6, 2]
    - ['wh', 4, 4]
    - ['wh', 5, 5]
    - ['wh', 1, 6]
    - ['wv', 2, 0]
    - ['wv', 6, 2]
    - ['wv', 5, 4]
    - ['wv', 2, 5]
    - ['wv', 3, 7]
    - ['gd', 4, 1]
    - ['rd', 5, 6]
